# Module: nginx
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/8.8/metricbeat-module-nginx.html

- module: nginx
  metricsets:
    - stubstatus
  period: 10s

  # Nginx hosts
  hosts: ["http://nginx"]

  # Path to server status. Default nginx_status
  server_status_path: "stub_status"

  #username: "user"
  #password: "secret"
